[package]
name = "aoc2018"
version = "0.1.0"
authors = ["Xavier Payn <xavier.payn@gmail.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.2.0"
aoc-runner-derive = "0.2.0"
itertools = "0.7.11"
bitvec = "0.8.0"
chrono = "0.4.6"
failure = "0.1.3"
time = "0.1.40"
